server:
  port: 6060
  servlet:
    context-path: /tsb
spring:
  application:
    name: tsb
  mvc:
     view:
       prefix: /jsp/
       suffix: .jsp
  datasource:
     url: postgres://evxybkkmiodzdd:857fa7799badf797bc9ae444b67dab94d2490e4a25d5a2d112019fbc75b8c42e@ec2-54-225-237-84.compute-1.amazonaws.com:5432/d3ftstv7m1o4k2
     databaseName:
     serverName:
     username: 
     password: 
     connectionTimeout: 10000
     cachePrepStmts: true
     prepStmtCacheSize: 250
     prepStmtCacheSqlLimit: 2048
     useServerPrepStmts: true

  jpa:
     database-platform: org.hibernate.dialect.PostgreSQLDialect
     database: MYSQL
     openInView: false
     show_sql: true
     generate-ddl: false
     hibernate:
        ddl-auto: none
        naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false